host: "localhost:3000"
host_email: "admin@sun-asterisk.com"
mail_user_name: "d498d93fcb7cb8"
mail_user_password: "2178c45cdc36f8"
mail_address: "sandbox.smtp.mailtrap.io"
mail_port: "2525"
secret_ket: "f534e56e-2f80-11ee-be56-0242ac120002"
