valid_email_regex: \A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z
max_length_name_20: 20
min_length_email_20: 20
max_length_email_255: 255
min_length_password_6: 6
gravatar_url: https://secure.gravatar.com/avatar/
max_length_name_100: 100
min_length_name_10: 10
max_5: 5
image_size_400: 400
format_date_f: "%d-%m-%Y"
min_length_text_10: 10
max_length_text_100: 100
max_length_text_254: 254
valid_image_format: image/jpeg image/gif image/png
validate_image_format: ["image/jpeg", "image/gif", "image/png"]
max_image_size_5_MB: 5
limit_image_area: [200, 200]
all_status_value: all
pagy_items_9: 9
order_status_approved: "approved"
order_status_cancelled: "cancelled"
